name: Compare the output with expected

on:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build Project
      run: cd ${{ github.workspace }} && mkdir build && cd build && cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/toolchain.cmake .. && make

    - name: Install gtest manually
      run: sudo apt-get install libgtest-dev && cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp ./lib/*.a /usr/lib

    - name: Build GTest
      run: |
        cd ${{ github.workspace }}/test
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/toolchain.cmake ..
        make

    - name: Generate Test Files
      run: |
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-1.csv ${{ github.workspace }}/test/Test_Samples/output/output1.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-2.csv ${{ github.workspace }}/test/Test_Samples/output/output2.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-3.csv ${{ github.workspace }}/test/Test_Samples/output/output3.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-4.csv ${{ github.workspace }}/test/Test_Samples/output/output4.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-5.csv ${{ github.workspace }}/test/Test_Samples/output/output5.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-6.csv ${{ github.workspace }}/test/Test_Samples/output/output6.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-7.csv ${{ github.workspace }}/test/Test_Samples/output/output7.csv
        ${{ github.workspace }}/build/exchange_application ${{ github.workspace }}/test/Test_Samples/input/orders-8.csv ${{ github.workspace }}/test/Test_Samples/output/output8.csv

    - name: Run Output Compare e2e test
      run: cd ${{ github.workspace }}/test/build && ./ExchangeEndToEndTest